--APP_PKG_TESTER_GETLIST

SELECT OBJECTVALUE2 
 , OBJECTVALUE3 
 , OBJECTVALUE4 
  FROM PSPCMTXT 
 WHERE OBJECTVALUE1 = :1
 
 
 
 --APP_PKG_TST_METHODS
 
 SELECT PACKAGEROOT 
 , QUALIFYPATH 
 , APPCLASSID 
 , EODS_OBJ_METHOD 
 , EODS_OBJ_METHOD 
  FROM ( 
 SELECT DISTINCT OBJECTVALUE1 PACKAGEROOT 
 , CASE WHEN OBJECTVALUE3='OnExecute' THEN ':' ELSE OBJECTVALUE2 END QUALIFYPATH 
 , CASE WHEN OBJECTVALUE3='OnExecute' THEN OBJECTVALUE2 ELSE OBJECTVALUE3 END APPCLASSID 
 , replace(CAST(REGEXP_SUBSTR(A.PCTEXT 
 ,'method\s\w+' 
 ,1 
 ,LOOP.OCCURS 
 ,'i') AS VARCHAR(50)) 
 ,'method ' 
 ,'') EODS_OBJ_METHOD 
  FROM PSPCMTXT A 
  , ( 
 SELECT ROWNUM OCCURS 
  FROM PS_JOB 
 WHERE ROWNUM<=50) LOOP 
 WHERE (OBJECTVALUE3='OnExecute' 
    OR OBJECTVALUE4='OnExecute') 
   AND CAST(REGEXP_SUBSTR(A.PCTEXT,'method\s(\w+)',1,LOOP.OCCURS,'i') AS VARCHAR(50)) <> ' ' 
   AND ((INSTR(A.PCTEXT,'private',1) > 0 
   AND INSTR(A.PCTEXT,'private',1) > INSTR(A.PCTEXT,CAST(REGEXP_SUBSTR(A.PCTEXT,'method\s(\w+)',1,LOOP.OCCURS,'i') AS VARCHAR(50)),1)) 
    OR (INSTR(A.PCTEXT,'private',1) = 0)) )
    
    
--UOA_APPPKG_MTHD

%Sql(UOA_APP_PKG_TST_METHODS) 
 WHERE APPCLASSID <> EODS_OBJ_METHOD
 
 
 --APPPKG_PARM
 
 SELECT %OperatorId 
 , 0 
 , ' ' 
 , ' ' 
 , ' ' 
  FROM DUAL
  
  
  
  --APPPKG_TST_PARM
  
  SELECT CAST(SUBSTR(A.PCTEXT 
 ,INSTR(A.PCTEXT 
 ,:1 || '(') + LENGTH(:1)+1 
 , INSTR(A.PCTEXT 
 ,')' 
 ,INSTR(A.PCTEXT 
 ,:1 || '('))-(INSTR(A.PCTEXT 
 ,:1 || '(') + LENGTH(:1)+1)) AS VARCHAR(200)) PARAMETERS 
  FROM PSPCMTXT A 
 WHERE OBJECTVALUE1=:2 
   AND CASE WHEN OBJECTVALUE3='OnExecute' THEN ':' ELSE OBJECTVALUE2 END = :3 
   AND CASE WHEN OBJECTVALUE3='OnExecute' THEN OBJECTVALUE2 ELSE OBJECTVALUE3 END =:4
   
   
   
   
   
   
   
   --STP_GET_PRCS_XML_FILE
   
   
   SELECT 'Y' 
 , to_char(trunc(CDM.RQSTDTTM) 
 ,'yyyymmdd') 
 , CDM.CONTENTID 
 , CDMF.FILENAME 
  FROM PS_CDM_LIST CDM 
  , PS_CDM_DIST_NODE CDMD 
  , PS_CDM_FILE_LIST CDMF 
 WHERE ((:1 > 0 
   AND CDM.CONTENTID=:1) 
    OR (:1 = 0 
   AND CDM.CONTENTID IN ( 
 SELECT RPT.CONTENTID 
  FROM PSRF_RINFO_TBL RPT 
  , PSRF_PGLET_VW PGL 
 WHERE PGL.USERID='a1221688' 
   AND PGL.PSRF_REPORT_NAME='GPAU_XML_GEN' 
   AND RPT.PSRF_REPORT_ID=PGL.PSRF_REPORT_ID))) 
   AND CDMD.DISTNODENAME=CDM.DISTNODENAME 
   AND CDMF.PRCSINSTANCE=CDM.PRCSINSTANCE 
   AND CDMF.CONTENTID=CDM.CONTENTID 
   AND CDMF.CDM_FILE_TYPE='XML' 
  ORDER BY CDM.PRCSINSTANCE DESC
